import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        ink: {
          navy: '#F0ECE3', // Soft airy background for sidebar instead of dark navy
          dark: '#EBE8E3', 
          border: 'rgba(0, 0, 0, 0.06)',
        },
        brand: {
          blue: '#1A73E8',
          'blue-hover': '#1558B0',
          green: '#00B386',
          coral: '#FF6B4A',
          'coral-light': '#FFF1EE',
          'coral-border': '#FECACA',
          'coral-text': '#C2410C',
          amber: '#F59E0B',
        },
        surface: {
          canvas: 'transparent',
          card: 'rgba(255, 255, 255, 0.35)',
          panel: 'rgba(255, 255, 255, 0.18)',
        },
        border: {
          DEFAULT: 'rgba(0,0,0,0.06)', // Very soft borders
        },
        text: {
          primary: '#0F1B2D',
          secondary: '#64748B',
          muted: '#94A3B8',
        },
        status: {
          success: '#15803D',
          'success-bg': '#ECFDF5',
          warning: '#92400E',
          'warning-bg': '#FFFBEB',
          danger: '#DC2626',
          'danger-bg': '#FEF2F2',
          opened: '#1D4ED8',
          'opened-bg': '#EFF6FF',
          clicked: '#6D28D9',
          'clicked-bg': '#F5F3FF',
        },
        landing: {
          "on-tertiary-container": "#657085",
          "secondary-container": "#e6e2dd",
          "primary-container": "#fdf2f2",
          "tertiary-container": "#f1f4ff",
          "surface-container": "#eeedf7",
          "inverse-on-surface": "#f1effa",
          "on-primary-fixed-variant": "#4c4546",
          "surface": "#fbf8ff",
          "primary-fixed-dim": "#cec4c4",
          "error-container": "#ffdad6",
          "on-secondary-fixed": "#1c1c19",
          "secondary-fixed-dim": "#c9c6c1",
          "outline": "#7f7575",
          "primary-fixed": "#ebe0e0",
          "on-secondary-fixed-variant": "#484743",
          "inverse-surface": "#2f3038",
          "on-primary-fixed": "#1f1a1b",
          "on-primary": "#ffffff",
          "inverse-primary": "#cec4c4",
          "secondary-fixed": "#e6e2dd",
          "on-secondary": "#ffffff",
          "tertiary-fixed-dim": "#bcc7de",
          "surface-container-highest": "#e3e1ec",
          "on-primary-container": "#756e6e",
          "surface-bright": "#fbf8ff",
          "outline-variant": "#d0c4c4",
          "error": "#ba1a1a",
          "on-surface": "#1a1b22",
          "on-background": "#1a1b22",
          "tertiary": "#545f73",
          "on-tertiary-fixed": "#111c2d",
          "on-tertiary": "#ffffff",
          "surface-container-lowest": "#ffffff",
          "surface-tint": "#645d5d",
          "on-tertiary-fixed-variant": "#3c475a",
          "primary": "#645d5d",
          "background": "#fbf8ff",
          "tertiary-fixed": "#d8e3fb",
          "on-secondary-container": "#666460",
          "surface-dim": "#dad9e3",
          "surface-container-high": "#e8e7f1",
          "on-error": "#ffffff",
          "secondary": "#605e5b",
          "on-surface-variant": "#4d4545",
          "surface-container-low": "#f4f2fd",
          "surface-variant": "#e3e1ec",
          "on-error-container": "#93000a"
        },
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        display: ['var(--font-dm-sans)', 'system-ui', 'sans-serif'],
        mono: ['Courier New', 'monospace'],
        "landing-headline-lg": ["Playfair Display"],
        "landing-body-sm": ["Inter"],
        "landing-display-lg": ["Playfair Display"],
        "landing-body-lg": ["Inter"],
        "landing-title-md": ["Inter"],
        "landing-label-caps": ["Inter"],
        "landing-headline-lg-mobile": ["Playfair Display"],
      },
      fontSize: {
        display: ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        h1: ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        h2: ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        body: ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        small: ['12px', { lineHeight: '1.5', fontWeight: '400' }],
        "landing-headline-lg": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "landing-body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "landing-display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "landing-body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "landing-title-md": ["20px", { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "500" }],
        "landing-label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "landing-headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "500" }],
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '7': '28px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '14': '56px',
        '16': '64px',
        'sidebar': '240px',
        'sidebar-collapsed': '64px',
        'topbar': '56px',
        'drawer': '480px',
        "landing-margin-desktop": "64px",
        "landing-unit": "4px",
        "landing-container-max-width": "1280px",
        "landing-gutter": "24px",
        "landing-margin-mobile": "16px",
      },
      borderRadius: {
        DEFAULT: '8px',
        lg: '12px',
        xl: '16px',
        pill: '9999px',
      },
      boxShadow: {
        card: '0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)',
        'card-hover': '0 4px 12px rgba(0,0,0,0.08)',
        drawer: '-4px 0 24px rgba(0,0,0,0.12)',
        modal: '0 20px 60px rgba(0,0,0,0.15)',
      },
      keyframes: {
        'slide-in-right': {
          from: { transform: 'translateX(100%)' },
          to: { transform: 'translateX(0)' },
        },
        'slide-out-right': {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(100%)' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'ping-dot': {
          '0%, 100%': { transform: 'scale(1)', opacity: '1' },
          '50%': { transform: 'scale(1.15)', opacity: '0.7' },
        },
      },
      animation: {
        'slide-in': 'slide-in-right 250ms cubic-bezier(0.4,0,0.2,1)',
        'slide-out': 'slide-out-right 250ms cubic-bezier(0.4,0,0.2,1)',
        'fade-in': 'fade-in 150ms cubic-bezier(0.4,0,0.2,1)',
        shimmer: 'shimmer 1.5s linear infinite',
        'ping-dot': 'ping-dot 600ms ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
export default config;
